baseURL = 'https://dotoleeoak.me/'
languageCode = 'en-us'
title = 'Jaemin Choi'
googleAnalytics = 'G-268FF6M4DY'

[[module.imports]]
path = "github.com/adityatelange/hugo-PaperMod"

[[menu.main]]
name = "Posts"
weight = 1
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "Résumé"
weight = 2
identifier = "resume"
url = "/resume/"

[params]
showtoc = false

[markup.highlight]
style = "github-dark"
